FROM tensorflow/tensorflow:latest-py3

RUN apt update && apt install -y python3 python3-pip python3-tk python3-numpy && apt clean

WORKDIR /app
COPY . /app

RUN pip --no-cache-dir install --upgrade pip setuptools
RUN pip --no-cache-dir install wheel
RUN pip --no-cache-dir install -r requirements.txt

CMD ["python3", "decensor.py"]
