FROM tensorflow/tensorflow:latest-py3

RUN apt-get update \
  && apt-get install -y python3 python3-pip python3-tk python3-numpy libsm6 libxext6 libxrender-dev \
  && apt-get clean
RUN apt-get install -y vim

WORKDIR /app
COPY . /app

RUN pip --no-cache-dir install --upgrade pip setuptools
RUN pip --no-cache-dir install wheel
RUN pip --no-cache-dir install -r requirements.txt

CMD ["python3", "decensor.py"]
